#------------------- Default configuration --------------------------

REEFTAS_STORAGE_DEVICE_DEFAULT="mmcblk0"
REEFTAS_STORAGE_DEVICE ??= "${REEFTAS_STORAGE_DEVICE_DEFAULT}"

# Default storage device.
REEFTAS_STORAGE_DEVICE_PATH_DEFAULT = "/dev/${REEFTAS_STORAGE_DEVICE}"
REEFTAS_STORAGE_DEVICE_PATH ??= "${REEFTAS_STORAGE_DEVICE_PATH_DEFAULT}"

#Base name of the device holding partitions
REEFTAS_STORAGE_DEVICE_BASE_PATH_DEFAULT = "${REEFTAS_STORAGE_DEVICE_PATH}p"
REEFTAS_STORAGE_DEVICE_BASE_PATH ??= "${REEFTAS_STORAGE_DEVICE_BASE_PATH_DEFAULT}"

REEFTAS_PART_NUMBER_START = "1"

#Default filesystem in reeftas
REEFTAS_FSTYPE_DEFAULT = "ext4"
REEFTAS_FSTYPE ??= "${REEFTAS_FSTYPE_DEFAULT}"

#Partition alignment. Default to 4k.
REEFTAS_PARTITION_ALIGNMENT_DEFAULT = "4096"
REEFTAS_PARTITION_ALIGNMENT ??="${REEFTAS_PARTITION_ALIGNMENT_DEFAULT}"


# Total size of sdcard image.
REEFTAS_STORAGE_TOTAL_SIZE_MB_DEFAULT = "2048"
REEFTAS_STORAGE_TOTAL_SIZE_MB ??= "${REEFTAS_STORAGE_TOTAL_SIZE_MB_DEFAULT}"

REEFTAS_PTABLE_TYPE_DEFAULT = "msdos"
REEFTAS_PTABLE_TYPE ??= "${REEFTAS_PTABLE_TYPE_DEFAULT}"

#-------------------------------------------------------------------------------
#Boot partition
#-------------------------------------------------------------------------------
REEFTAS_BOOT_PART_NUMBER ??= "${REEFTAS_PART_NUMBER_START}"
REEFTAS_BOOT_PART_DEFAULT = "${REEFTAS_STORAGE_DEVICE_BASE_PATH}${REEFTAS_BOOT_PART_NUMBER}"
REEFTAS_BOOT_PART ??="${REEFTAS_BOOT_PART_DEFAULT}"

#Boot partiton size
REEFTAS_BOOT_PART_SIZE_MB_DEFAULT = "48"
REEFTAS_BOOT_PART_SIZE_MB ??= "${REEFTAS_BOOT_PART_SIZE_MB_DEFAULT}"

#Boot partiton fstype
REEFTAS_BOOT_PART_FSTYPE_DEFAULT = "vfat"
REEFTAS_BOOT_PART_FSTYPE ??= "${REEFTAS_BOOT_PART_FSTYPE_DEFAULT}"
#-------------------------------------------------------------------------------
#A/B rootfs partition
#-------------------------------------------------------------------------------
REEFTAS_ROOTFS_PART_A_PART_NUMBER ??= "${@eval('${REEFTAS_BOOT_PART_NUMBER} + 1')}"
REEFTAS_ROOTFS_PART_A_DEFAULT = "${REEFTAS_STORAGE_DEVICE_BASE_PATH}${REEFTAS_ROOTFS_PART_A_PART_NUMBER}"
REEFTAS_ROOTFS_PART_A ??= "${REEFTAS_ROOTFS_PART_A_DEFAULT}"

REEFTAS_ROOTFS_PART_A_FSTYPE_DEFAULT = "${REEFTAS_FSTYPE}"
REEFTAS_ROOTFS_PART_A_FSTYPE ??= "${REEFTAS_ROOTFS_PART_A_FSTYPE_DEFAULT}"

REEFTAS_ROOTFS_PART_A_LABEL_DEFAULT ??= "primary"
REEFTAS_ROOTFS_PART_A_LABEL ??= "${REEFTAS_ROOTFS_PART_A_LABEL_DEFAULT}"

REEFTAS_ROOTFS_PART_B_PART_NUMBER ??= "${@eval('${REEFTAS_ROOTFS_PART_A_PART_NUMBER} + 1')}"
REEFTAS_ROOTFS_PART_B_DEFAULT = "${REEFTAS_STORAGE_DEVICE_BASE_PATH}${REEFTAS_ROOTFS_PART_B_PART_NUMBER}"
REEFTAS_ROOTFS_PART_B ??= "${REEFTAS_ROOTFS_PART_B_DEFAULT}"

REEFTAS_ROOTFS_PART_B_FSTYPE_DEFAULT = "${REEFTAS_FSTYPE}"
REEFTAS_ROOTFS_PART_B_FSTYPE ??= "${REEFTAS_ROOTFS_PART_B_FSTYPE_DEFAULT}"

REEFTAS_ROOTFS_PART_B_LABEL_DEFAULT ??= "secondary"
REEFTAS_ROOTFS_PART_B_LABEL ??= "${REEFTAS_ROOTFS_PART_B_LABEL_DEFAULT}"
#-------------------------------------------------------------------------------
#Var partition
#-------------------------------------------------------------------------------#
REEFTAS_VAR_PART_NUMBER ??= "${@eval('${REEFTAS_ROOTFS_PART_B_PART_NUMBER} + 1')}"
REEFTAS_VAR_PART_DEFAULT = "${REEFTAS_STORAGE_DEVICE_BASE_PATH}${REEFTAS_VAR_PART_NUMBER}"
REEFTAS_VAR_PART ??= "${REEFTAS_VAR_PART_DEFAULT}"

#Var partition size
REEFTAS_VAR_PART_SIZE_MB_DEFAULT = "128"
REEFTAS_VAR_PART_SIZE_DEFAULT = "${@eval('${REEFTAS_VAR_PART_SIZE_MB} * 1024')}"
REEFTAS_VAR_PART_SIZE ??= "${REEFTAS_VAR_PART_SIZE_DEFAULT}"
REEFTAS_VAR_PART_SIZE_MB ??= "${REEFTAS_VAR_PART_SIZE_MB_DEFAULT}"

#var partition mount point
REEFTAS_VAR_PART_MOUNT_POINT_DEFAULT = "/var"
REEFTAS_VAR_PART_MOUNT_POINT ??= "${REEFTAS_VAR_PART_MOUNT_POINT_DEFAULT}"

REEFTAS_VAR_FSTYPE_DEFAULT = "${REEFTAS_FSTYPE}"
REEFTAS_VAR_FSTYPE ??= "${REEFTAS_ROOTFS_PART_A_FSTYPE_DEFAULT}"

REEFTAS_VAR_LABEL_DEFAULT ??= "var"
REEFTAS_VAR_LABEL ??= "${REEFTAS_VAR_LABEL_DEFAULT}"

#-------------------------------------------------------------------------------
#Reeftas data partition
#-------------------------------------------------------------------------------
REEFTAS_DATA_PART_NUMBER ??= "${@eval('${REEFTAS_VAR_PART_NUMBER} + 1')}"
REEFTAS_DATA_PART_DEFAULT = "${REEFTAS_STORAGE_DEVICE_BASE_PATH}${REEFTAS_DATA_PART_NUMBER}"
REEFTAS_DATA_PART ??= "${REEFTAS_DATA_PART_DEFAULT}"

#Data partiton size
REEFTAS_DATA_PART_SIZE_MB_DEFAULT = "512"
REEFTAS_DATA_PART_SIZE_DEFAULT = "${@eval('${REEFTAS_DATA_PART_SIZE_MB} * 1024')}"
REEFTAS_DATA_PART_SIZE_MB ??= "${REEFTAS_DATA_PART_SIZE_MB_DEFAULT}"
REEFTAS_DATA_PART_SIZE ??= "${REEFTAS_DATA_PART_SIZE_DEFAULT}"

#Reeftas data mount point
REEFTAS_DATA_MOUNT_POINT_DEFAULT = "/data"
REEFTAS_DATA_MOUNT_POINT ??= "${REEFTAS_DATA_MOUNT_POINT_DEFAULT}"

REEFTAS_DATA_FSTYPE_DEFAULT = "${REEFTAS_FSTYPE}"
REEFTAS_DATA_FSTYPE ??= "${REEFTAS_DATA_FSTYPE_DEFAULT}"

REEFTAS_DATA_LABEL_DEFAULT ??= "var"
REEFTAS_DATA_LABEL ??= "${REEFTAS_DATA_LABEL_DEFAULT}"

#----------------------------------------------------------------------
# Reeftas User and Group
#----------------------------------------------------------------------
REEFTAS_USER="reeftas"
REEFTAS_GROUP="reeftas"

include reeftas-uboot.inc
include reeftas-setup-install.inc
include reeftas-wic.inc
